#!/bin/bash


if [[ $(pwd) = */scripts ]]; then
 cd ..
fi


if [[ $# -ne 2 ]];then
 echo "ERROR Usage deployHelm [LOCAL | MINIKUBE | IBMCLOUD | ICP] tag"
 exit 1
fi


../scripts/deployHelm "orderqueryms" $1 $2
