FROM ibmjava:8-sdk as builder
RUN apt-get update && apt-get install -y maven

WORKDIR "/app"
ADD . /app
RUN mvn install -DskipIT

FROM websphere-liberty:webProfile7
LABEL maintainer="IBM Java Engineering at IBM Cloud"
# 3 next lines need to be there to avoid NPE on javametrics-rest, javametrics-dash,
COPY --from=builder /app/target/liberty/wlp/usr/servers/defaultServer /config/
COPY --from=builder /app/target/liberty/wlp/usr/shared/resources /config/resources/
COPY --from=builder /app/src/main/liberty/config/jvmbx.options /config/jvm.options
# Grant write access to apps folder, this is to support old and new docker versions.
# Liberty document reference : https://hub.docker.com/_/websphere-liberty/
USER root
COPY es-cert.der /tmp/es-cert.der
RUN apt-get update -q -y && apt-get dist-upgrade -q -y && chmod g+w /config/apps &&\
    echo yes | keytool -importcert -alias startssl -keystore \
    $JAVA_HOME/lib/security/cacerts -storepass changeit -file /tmp/es-cert.der 
USER 1001

# install any missing features required by server config
RUN installUtility install --acceptLicense defaultServer 


# Upgrade to production license if URL to JAR provided
ARG LICENSE_JAR_URL
RUN \ 
  if [ $LICENSE_JAR_URL ]; then \
    wget $LICENSE_JAR_URL -O /tmp/license.jar \
    && java -jar /tmp/license.jar -acceptLicense /opt/ibm \
    && rm /tmp/license.jar; \
  fi
