#!/bin/bash

if [[ $# -ne 4 ]];then
  echo "deployHelm <servicename> <namespace> <env> <tag> "
  exit
fi

msname=$1
ns=$2
chart=$(ls ./chart/| grep $msname)
kname="kc-"$chart
kcenv=$3
kctag=$4

source ../refarch-kc/scripts/setenv.sh $kcenv

echo "Deploy helm chart for $chart project to $ns"

verifyPod(){
  kubectl logs $1 -n $ns
}

echo "############################"
oq=$(helm list | grep $kname | awk '{print $1}')
if [[ -z "$oq" ]]
then
  echo "$chart release not deployed... which is expected so deploy it"
  cd ./chart
  if [[ "$kcenv" == "MINIKUBE" ]]
  then
    helm install $chart/ --name $msname --set image.repository=ibmcase/$kname --set image.tag=$kctag --set image.pullSecret= --set image.pullPolicy=Never --set eventstreams.brokers=kafkabitmani:9092 --set eventstreams.env=MINIKUBE --namespace $ns
  else
    helm install $chart/ --name $msname --namespace $ns
  fi
  sleep 4
else
    echo "$kname release deployed, here is the pod logs"
    helm upgrade $msname $chart/
    helm history $msname
fi

podId=$(kubectl get pods -n $ns | grep $msname | awk '{print $1}')
verifyPod $podId