name: Publish order-command Docker
on:
  push:
    paths:
      - 'order-command-ms/**'
  pull_request:
    paths:
      - 'order-command-ms/**'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ibm-cloud-architecture/kcontainer-order-command-ms
      IMAGE_TAG: latest
      WORKDIR: order-command-ms
      DOCKERFILE: Dockerfile.multistage
    steps:
    - uses: actions/checkout@master
    - name: Build and push container
      run: |
         docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} && \
         docker build -t $IMAGE_NAME:$IMAGE_TAG -f $WORKDIR/$DOCKERFILE $WORKDIR && \
         docker push $IMAGE_NAME:$IMAGE_TAG
